### ISSUE TITLE
Power Saver defaults to Turn Display Off to "Never"

### ISSUE THREAD

**Issue by cbkemp** [treasurebox/MagicKeys#10]
When installed on Latest Yosemite, my Display Settings are set to turn off "Never" and I am unable to move the slider back to some other time (say 15 Minutes) without the slider moving back to "Never"

**Comment by treasurebox** [comment]
Hi!

Again, are you perfectly sure this is caused by Magic Keys? This seems unrelated to how Magic Keys works.

**Comment by cbkemp** [comment]
I am unable to reproduce now.

I had the problem and did some googling and saw that the most common 
issues relating to the Spotlight search in System Preferences were 
caused by preference panes. and I uninstalled Magic Keys and it went 
away. I reinstalled to try to reproduce, and it will not reproduce. So I 
am using it again.

<http://www.triumvircorp.com>


> treasurebox <mailto:notifications@github.com>
> July 14, 2015 at 5:48 AM
>
> Hi!
>
> Again, are you perfectly sure this is caused by Magic Keys? This seems 
> unrelated to how Magic Keys works.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/treasurebox/MagicKeys/issues/10#issuecomment-121198711>.
>


-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the sender. Please 
note that any views or opinions presented in this email are solely those of 
the author and do not necessarily represent those of the company. Finally, 
the recipient should check this email and any attachments for the presence 
of viruses. The company accepts no liability for any damage caused by any 
virus transmitted by this email.

**Comment by treasurebox** [comment]
Thanks for letting me know! If you ever encounter the problem again, please tell me about it!
