### ISSUE TITLE
System Preferences Spolight Search Breaks

### ISSUE THREAD

**Issue by cbkemp** [treasurebox/MagicKeys#9]
Installed on latest Yosemite and when Magic Keys is installed, searching in System Preferences does not work.

**Comment by treasurebox** [comment]
Hi! Are you sure it's related to Magic Keys? I am unable to reproduce the problem. Could you please post a video on what exactly happens? (Quicktime Player can make a Screen Recording)

**Comment by cbkemp** [comment]
I am unable to reproduce now.

I had the problem and did some googling and saw that the most common 
issues relating to the Spotlight search in System Preferences were 
caused by preference panes. and I uninstalled Magic Keys and it went 
away. I reinstalled to try to reproduce, and it will not reproduce. So I 
am using it again.

> treasurebox <mailto:notifications@github.com>
> July 14, 2015 at 5:45 AM
>
> Hi! Are you sure it's related to Magic Keys? I am unable to reproduce 
> the problem. Could you please post a video on what exactly happens? 
> (Quicktime Player can make a Screen Recording)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/treasurebox/MagicKeys/issues/9#issuecomment-121197956>.
>


-- 
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the sender. Please 
note that any views or opinions presented in this email are solely those of 
the author and do not necessarily represent those of the company. Finally, 
the recipient should check this email and any attachments for the presence 
of viruses. The company accepts no liability for any damage caused by any 
virus transmitted by this email.

**Comment by treasurebox** [comment]
Thanks for letting me know! So the issue is not in Magic Keys itself, but in System Preferences.app . That said, if you ever encounter it again - assuming you need Magic Keys because of Gear -  please let me know, and I'll send you a version of Gear which does not need Magic Keys.
